### PR TITLE
better GET error handling

### PR DESCRIPTION
**Pull request by buhman**
- fix usage of `accepts` `$.ajax` parameter
- json is not decoded on `dataType: text`, so try it before giving up

### CODE REVIEW

**Comment by buhman** [comment]
fucking `GET`. why do we need to support that awful route? Also, relevant upstream commit ptpb/pb@de2b69e8f976cea12139100349a246ad46b490f4 ; you're welcome.

**Comment by buhman** [comment]
> Why are you attempting to use dataType: 'text' anyway?

If the paste body in a successful GET happens to be valid json, we don't want it decoded.

**Comment by sudokode** [comment]
> If the paste body in a successful GET happens to be valid json, we don't want it decoded.

Why? Don't we only deal with JSON?

**Comment by buhman** [comment]
Eh? paste GET responses (paste content) could be literally anything. We don't want to parse user data, we only want to parse data from pb itself.

**Comment by sudokode** [comment]
Oh derp nevermind.

**Pull request merged**
