### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by buhman**
**styles**:
- non-bootstrap styles were removed
- seriously, wtf?

**layout**:
- restructured form layout to match bootstrap
- accessibility [greatly](https://ptpb.pw/HIlV.png) improved on small displays
- moved response display from random div to bootstrap [alert](https://ptpb.pw/tSMK.png)

**code**:
- cleaner separation of API, view, and controller/event code
- use `multipart/form-data` in api requests instead of
  `application/x-www-form-urlencoded`
- remove native browser alerts

**animation**:
- use spinner animations during api requests

**regressions/changes**:
- the `load` button and field are unimplemented
- `sunset` and `vanity` pass value directly to API
- failure handling is arguably slightly less robust

### CODE REVIEW

**Comment by buhman** [comment]
A few other thoughts:
- Alerts currently linger forever; should they fade after some time, or be cleared after each paste?
- Should buttons be disabled while they are spinning?
- I can imagine someone typing some paste content, then pushing `Upload File` accidentally. Should it be possible to clear the uploaded file without clearing all fields?
- I've never done a working upload progress bar before; might be fun.
- More colors (alerts, buttons)?
- More animations?
- I thought maybe [popovers](https://getbootstrap.com/javascript/#popovers) that show the proposed API request as you hover over each button might be pretty cool.

**Comment by sudokode** [comment]
Is the expire input just gonna be a seconds entry? Big boring text box for that.

> seconds

**Comment by buhman** [comment]
> Big boring text box for that

How about [this](https://jsfiddle.net/0r1ka4fe/); you swap between seconds/hours and datetime. `pb` can support parsing datetime sunsets easily. bootstrap-datetime can also be configured to show the clock widget instead of the calendar by default if we think 'an hour from now' is a more likely selection than 'next week'.

**Comment by sudokode** [comment]
> How about this

That's sweet.

**Comment by sudokode** [comment]
```
-----------------------------6742606011366069413581626932
Content-Disposition: form-data; name="content"

235423523 #9 
-----------------------------6742606011366069413581626932--
```

Getting a `404` when trying to paste. Returns `status: no content` and the Paste button spinner stays up with no visible error. Might be the param name, `c` instead of `content`.

**Comment by buhman** [comment]
> `status: no content`
> param name, c instead of content

Heh. https://github.com/ptpb/pb/commit/a0e3934de00f135b52b05517d65adde870fc4e71 changed that, but it wasn't deployed until just now. Previously, `content` was a valid key in `application/json` requests, but not in others. Now all variants are accepted in all request body types.

**Comment by buhman** [comment]
> Paste button spinner stays up with no visible error

A unrelated problem, but still a problem.

**Comment by buhman** [comment]
yay

**Pull request merged**
